- name: restart k8s
  service:
    name: kube-apiserver
    state: restarted
- name: restart etcd
  service:
    name: etcd
    state: restarted
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
